language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
install:
  - composer install
script:
  - composer test
notifications:
  irc:
    channels:
      - "chat.freenode.net#jquery-dev"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} %{author}): %{message} - %{build_url}"
